version: "3"
services:
  redis-server:
    image: redis-server:latest
    ports:
      - "6379:6379"
    networks:
      my-network:
        ipv4_address: 10.1.0.2
  client-go:
    image: client-go:latest
    networks:
      my-network:
        ipv4_address: 10.1.0.3

networks:
  my-network:
    driver: bridge
    ipam:
      config:
        - subnet: 10.1.0.0/24
